//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string UPDV1 = "updv1";
        
        public const string WEELONE = "weelone";
        
        public const string BACKCRAWL = "backcrawl";
        
        public const string HYBRID = "hybrid";
        
        public const string MAXVIBRATE = "maxvibrate";
        
        public const string FORCRAWL = "forcrawl";
        
        public const string FLOOR_RUMBLE = "floor_rumble";
    }
}
